
DROP TABLE IF EXISTS `share`;

CREATE TABLE IF NOT EXISTS `share` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`orgid` CHAR(16) NOT NULL COLLATE utf8_bin,
	`documentid` CHAR(16) NOT NULL COLLATE utf8_bin,
	`userid` CHAR(16) DEFAULT '' COLLATE utf8_bin,
	`email` NVARCHAR(250) NOT NULL DEFAULT '',
	`message` NVARCHAR(500) NOT NULL DEFAULT '',
	`viewed` VARCHAR(500) NOT NULL DEFAULT '',
	`secret` VARCHAR(200) NOT NULL DEFAULT '',
	`expires` CHAR(16) DEFAULT '' COLLATE utf8_bin,
	`active` BOOL NOT NULL DEFAULT 1,
	`created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_id PRIMARY KEY (id))
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci
ENGINE =  InnoDB;
